// <auto-generated />
using System;
using Luciferin.DataLayer.Storage.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Luciferin.DataLayer.Storage.Postgres.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Luciferin.DataLayer.Storage.Entities.ImportStatistic", b =>
                {
                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExistingTransactionsFiltered")
                        .HasColumnType("integer");

                    b.Property<int>("NewTransactions")
                        .HasColumnType("integer");

                    b.Property<bool>("StartingBalanceSet")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalAccounts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFireflyTransactions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRetrievedTransactions")
                        .HasColumnType("integer");

                    b.Property<int>("TransfersFiltered")
                        .HasColumnType("integer");

                    b.HasKey("ImportDate");

                    b.ToTable("ImportStatistics");
                });

            modelBuilder.Entity("Luciferin.DataLayer.Storage.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnOrder(0);

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer");

                    b.Property<string>("StringValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TimeSpanValue")
                        .HasColumnType("interval");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnOrder(1);

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
